"""Initial schema

Revision ID: 0001_initial
Revises:
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001_initial"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parents",
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=16), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("auth_uuid", sa.Uuid(), nullable=False),
        sa.Column(
            "auth_expires_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now() + interval '7 days'"),
            nullable=False,
        ),
        sa.Column("auth_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("phone ~ '^\\+[1-9][0-9]{7,14}$'", name=op.f("ck_parents_phone_e164")),
        sa.CheckConstraint(
            "length(trim(first_name)) > 0", name=op.f("ck_parents_first_name_not_empty")
        ),
        sa.CheckConstraint(
            "length(trim(last_name)) > 0", name=op.f("ck_parents_last_name_not_empty")
        ),
        sa.CheckConstraint(
            "telegram_id IS NULL OR telegram_id > 0", name=op.f("ck_parents_telegram_id_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_parents")),
        sa.UniqueConstraint("auth_uuid", name=op.f("uq_parents_auth_uuid")),
    )
    op.create_index(op.f("ix_parents_phone"), "parents", ["phone"], unique=False)
    op.create_table(
        "staff",
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=16), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "superadmin",
                "admin",
                "teacher",
                name="role",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="teacher",
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("active", "inactive", name="status", native_enum=False, create_constraint=True),
            server_default="active",
            nullable=False,
        ),
        sa.Column(
            "permissions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("telegram_id", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("auth_uuid", sa.Uuid(), nullable=False),
        sa.Column(
            "auth_expires_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now() + interval '7 days'"),
            nullable=False,
        ),
        sa.Column("auth_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "jsonb_typeof(permissions) = 'array'", name=op.f("ck_staff_permissions_array")
        ),
        sa.CheckConstraint("phone ~ '^\\+[1-9][0-9]{7,14}$'", name=op.f("ck_staff_phone_e164")),
        sa.CheckConstraint("username ~ '^[a-z0-9_]{3,64}$'", name=op.f("ck_staff_username_format")),
        sa.CheckConstraint(
            "length(trim(first_name)) > 0", name=op.f("ck_staff_first_name_not_empty")
        ),
        sa.CheckConstraint(
            "length(trim(last_name)) > 0", name=op.f("ck_staff_last_name_not_empty")
        ),
        sa.CheckConstraint(
            "telegram_id IS NULL OR telegram_id > 0", name=op.f("ck_staff_telegram_id_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_staff")),
        sa.UniqueConstraint("auth_uuid", name=op.f("uq_staff_auth_uuid")),
        sa.UniqueConstraint("phone", name=op.f("uq_staff_phone")),
        sa.UniqueConstraint("telegram_id", name=op.f("uq_staff_telegram_id")),
        sa.UniqueConstraint("username", name=op.f("uq_staff_username")),
    )
    op.create_index(op.f("ix_staff_status"), "staff", ["status"], unique=False)
    op.create_table(
        "subjects",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("length(trim(name)) > 0", name=op.f("ck_subjects_name_not_empty")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subjects")),
        sa.UniqueConstraint("name", name=op.f("uq_subjects_name")),
    )
    op.create_table(
        "auth_sessions",
        sa.Column("staff_id", sa.Uuid(), nullable=False),
        sa.Column(
            "portal",
            sa.Enum("admin", "teacher", name="portal", native_enum=False, create_constraint=True),
            nullable=False,
        ),
        sa.Column("access_token_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_token_hash", sa.String(length=64), nullable=False),
        sa.Column("access_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "access_expires_at <= expires_at", name=op.f("ck_auth_sessions_access_expiry_valid")
        ),
        sa.CheckConstraint("expires_at > created_at", name=op.f("ck_auth_sessions_expiry_valid")),
        sa.CheckConstraint(
            "length(access_token_hash) = 64", name=op.f("ck_auth_sessions_access_hash_length")
        ),
        sa.CheckConstraint(
            "length(csrf_token_hash) = 64", name=op.f("ck_auth_sessions_csrf_hash_length")
        ),
        sa.ForeignKeyConstraint(
            ["staff_id"],
            ["staff.id"],
            name=op.f("fk_auth_sessions_staff_id_staff"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_sessions")),
        sa.UniqueConstraint("access_token_hash", name=op.f("uq_auth_sessions_access_token_hash")),
    )
    op.create_index(
        op.f("ix_auth_sessions_expires_at"), "auth_sessions", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_auth_sessions_staff_id"), "auth_sessions", ["staff_id"], unique=False)
    op.create_table(
        "groups",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("teacher_id", sa.Uuid(), nullable=False),
        sa.Column("monthly_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("max_students", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "inactive", name="status", native_enum=False, create_constraint=True),
            server_default="active",
            nullable=False,
        ),
        sa.Column("days_of_week", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("room_number", sa.String(length=30), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "CASE WHEN jsonb_typeof(days_of_week) = 'array' THEN "
            "jsonb_array_length(days_of_week) BETWEEN 1 AND 7 "
            "AND days_of_week <@ '[1,2,3,4,5,6,7]'::jsonb ELSE false END",
            name=op.f("ck_groups_days_valid"),
        ),
        sa.CheckConstraint("length(trim(name)) > 0", name=op.f("ck_groups_name_not_empty")),
        sa.CheckConstraint(
            "max_students BETWEEN 1 AND 1000", name=op.f("ck_groups_capacity_valid")
        ),
        sa.CheckConstraint("monthly_price >= 0", name=op.f("ck_groups_price_nonnegative")),
        sa.CheckConstraint("start_time < end_time", name=op.f("ck_groups_time_order")),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
            name=op.f("fk_groups_subject_id_subjects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["staff.id"],
            name=op.f("fk_groups_teacher_id_staff"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_groups")),
    )
    op.create_index(op.f("ix_groups_status"), "groups", ["status"], unique=False)
    op.create_index(op.f("ix_groups_teacher_id"), "groups", ["teacher_id"], unique=False)
    op.create_table(
        "otp_challenges",
        sa.Column("staff_id", sa.Uuid(), nullable=False),
        sa.Column(
            "portal",
            sa.Enum("admin", "teacher", name="portal", native_enum=False, create_constraint=True),
            nullable=False,
        ),
        sa.Column(
            "purpose",
            sa.Enum("login", "reset", name="purpose", native_enum=False, create_constraint=True),
            nullable=False,
        ),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "attempts BETWEEN 0 AND 5", name=op.f("ck_otp_challenges_attempts_valid")
        ),
        sa.CheckConstraint("expires_at > created_at", name=op.f("ck_otp_challenges_expiry_valid")),
        sa.CheckConstraint("length(code_hash) = 64", name=op.f("ck_otp_challenges_hash_length")),
        sa.ForeignKeyConstraint(
            ["staff_id"],
            ["staff.id"],
            name=op.f("fk_otp_challenges_staff_id_staff"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_otp_challenges")),
    )
    op.create_index(
        op.f("ix_otp_challenges_expires_at"), "otp_challenges", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_otp_challenges_staff_id"), "otp_challenges", ["staff_id"], unique=False
    )
    op.create_table(
        "system_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bot_token_encrypted", sa.Text(), nullable=True),
        sa.Column("bot_username", sa.String(length=64), nullable=True),
        sa.Column("version", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("active_version", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("last_update_id", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("changed_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(parameters) = 'object'", name=op.f("ck_system_settings_parameters_object")
        ),
        sa.CheckConstraint("id = 1", name=op.f("ck_system_settings_singleton")),
        sa.CheckConstraint(
            "version >= 0 AND active_version >= 0", name=op.f("ck_system_settings_version_valid")
        ),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["staff.id"],
            name=op.f("fk_system_settings_changed_by_staff"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_system_settings")),
    )
    op.create_table(
        "attendance_batches",
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("finalized_by", sa.Uuid(), nullable=False),
        sa.Column(
            "finalized_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["finalized_by"],
            ["staff.id"],
            name=op.f("fk_attendance_batches_finalized_by_staff"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
            name=op.f("fk_attendance_batches_group_id_groups"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attendance_batches")),
        sa.UniqueConstraint("group_id", "date", name="uq_attendance_batches_group_date"),
    )
    op.create_index(
        op.f("ix_attendance_batches_date"), "attendance_batches", ["date"], unique=False
    )
    op.create_index(
        op.f("ix_attendance_batches_group_id"), "attendance_batches", ["group_id"], unique=False
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("length(token_hash) = 64", name=op.f("ck_refresh_tokens_hash_length")),
        sa.ForeignKeyConstraint(
            ["replaced_by_id"],
            ["refresh_tokens.id"],
            name=op.f("fk_refresh_tokens_replaced_by_id_refresh_tokens"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["auth_sessions.id"],
            name=op.f("fk_refresh_tokens_session_id_auth_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_tokens_token_hash")),
    )
    op.create_index(
        op.f("ix_refresh_tokens_expires_at"), "refresh_tokens", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_refresh_tokens_session_id"), "refresh_tokens", ["session_id"], unique=False
    )
    op.create_table(
        "students",
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=16), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "inactive", name="status", native_enum=False, create_constraint=True),
            server_default="active",
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("auth_uuid", sa.Uuid(), nullable=False),
        sa.Column(
            "auth_expires_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now() + interval '7 days'"),
            nullable=False,
        ),
        sa.Column("auth_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("phone ~ '^\\+[1-9][0-9]{7,14}$'", name=op.f("ck_students_phone_e164")),
        sa.CheckConstraint("age BETWEEN 3 AND 100", name=op.f("ck_students_age_valid")),
        sa.CheckConstraint(
            "length(trim(first_name)) > 0", name=op.f("ck_students_first_name_not_empty")
        ),
        sa.CheckConstraint(
            "length(trim(last_name)) > 0", name=op.f("ck_students_last_name_not_empty")
        ),
        sa.CheckConstraint(
            "telegram_id IS NULL OR telegram_id > 0", name=op.f("ck_students_telegram_id_positive")
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
            name=op.f("fk_students_group_id_groups"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["parents.id"],
            name=op.f("fk_students_parent_id_parents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_students")),
        sa.UniqueConstraint("auth_uuid", name=op.f("uq_students_auth_uuid")),
    )
    op.create_index(op.f("ix_students_group_id"), "students", ["group_id"], unique=False)
    op.create_index(op.f("ix_students_parent_id"), "students", ["parent_id"], unique=False)
    op.create_index(op.f("ix_students_status"), "students", ["status"], unique=False)
    op.create_table(
        "attendance",
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "present",
                "absent",
                "late",
                name="attendance_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("marked_by", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "note IS NULL OR length(note) <= 2000", name=op.f("ck_attendance_note_length")
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["attendance_batches.id"],
            name=op.f("fk_attendance_batch_id_attendance_batches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
            name=op.f("fk_attendance_group_id_groups"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["marked_by"],
            ["staff.id"],
            name=op.f("fk_attendance_marked_by_staff"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_attendance_student_id_students"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attendance")),
        sa.UniqueConstraint(
            "group_id", "student_id", "date", name="uq_attendance_group_student_date"
        ),
    )
    op.create_index(op.f("ix_attendance_batch_id"), "attendance", ["batch_id"], unique=False)
    op.create_index(op.f("ix_attendance_date"), "attendance", ["date"], unique=False)
    op.create_index(op.f("ix_attendance_group_id"), "attendance", ["group_id"], unique=False)
    op.create_index(op.f("ix_attendance_marked_by"), "attendance", ["marked_by"], unique=False)
    op.create_index(op.f("ix_attendance_student_id"), "attendance", ["student_id"], unique=False)
    op.create_table(
        "notification_outbox",
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("attendance_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "processing",
                "delivered",
                "skipped",
                "failed",
                name="outbox_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.Uuid(), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "jsonb_typeof(payload) = 'object'", name=op.f("ck_notification_outbox_payload_object")
        ),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_notification_outbox_attempts_valid")),
        sa.CheckConstraint(
            "telegram_id IS NULL OR telegram_id > 0",
            name=op.f("ck_notification_outbox_telegram_id_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["attendance_id"],
            ["attendance.id"],
            name=op.f("fk_notification_outbox_attendance_id_attendance"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["parents.id"],
            name=op.f("fk_notification_outbox_parent_id_parents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_outbox")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_notification_outbox_idempotency_key")),
    )
    op.create_index(
        "ix_notification_outbox_pending",
        "notification_outbox",
        ["status", "available_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_notification_outbox_pending", table_name="notification_outbox")
    op.drop_table("notification_outbox")
    op.drop_index(op.f("ix_attendance_student_id"), table_name="attendance")
    op.drop_index(op.f("ix_attendance_marked_by"), table_name="attendance")
    op.drop_index(op.f("ix_attendance_group_id"), table_name="attendance")
    op.drop_index(op.f("ix_attendance_date"), table_name="attendance")
    op.drop_index(op.f("ix_attendance_batch_id"), table_name="attendance")
    op.drop_table("attendance")
    op.drop_index(op.f("ix_students_status"), table_name="students")
    op.drop_index(op.f("ix_students_parent_id"), table_name="students")
    op.drop_index(op.f("ix_students_group_id"), table_name="students")
    op.drop_table("students")
    op.drop_index(op.f("ix_refresh_tokens_session_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_expires_at"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_attendance_batches_group_id"), table_name="attendance_batches")
    op.drop_index(op.f("ix_attendance_batches_date"), table_name="attendance_batches")
    op.drop_table("attendance_batches")
    op.drop_table("system_settings")
    op.drop_index(op.f("ix_otp_challenges_staff_id"), table_name="otp_challenges")
    op.drop_index(op.f("ix_otp_challenges_expires_at"), table_name="otp_challenges")
    op.drop_table("otp_challenges")
    op.drop_index(op.f("ix_groups_teacher_id"), table_name="groups")
    op.drop_index(op.f("ix_groups_status"), table_name="groups")
    op.drop_table("groups")
    op.drop_index(op.f("ix_auth_sessions_staff_id"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_expires_at"), table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_table("subjects")
    op.drop_index(op.f("ix_staff_status"), table_name="staff")
    op.drop_table("staff")
    op.drop_index(op.f("ix_parents_phone"), table_name="parents")
    op.drop_table("parents")
    # ### end Alembic commands ###
